### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-deployment#122]
Are these configurations going to be versioned so it's easy to talk about what's been deployed when using this repo over time, similar to how cf-deployment is versioning itself?

**Comment by cppforlife** [comment]
@geofffranks we werent planning to do anything fancy. any bump in bosh-deployment may result in asking for new properties but we try really hard to not do so. there are existing plans for example to use this as a base for PWS directors.

**Comment by geofffranks** [comment]
Having tags or versions on here would make it easy for CI pipelines to consume the bosh.yml + ops files from here, and know that every time the pipeline runs, we'll be getting the same manifests generated, unless we bump the pipeline to look at a new tag. Without that, each time we run the a deployment of our bosh via CI, we might get a new manifest for bosh that may or may not be what we ready to deploy.

**Comment by pivotal-jamil-shamy** [comment]
I think having tags in bosh-deployment for all supported versions of bosh (264.x, 263.x, etc) is beneficial for users.

**Comment by Benjamintf1** [comment]
We recently were trying to deploy a cf using bosh-deployment, cf-deployment and cf-deployment-concourse-tasks. We suspect that because of the bosh upgrade, our previously working cf-deployment config is breaking. The lookup sql-db.service.cf.internal on **IP**: no such host is repeatedly failing. We theorize this has to do with bosh-dns or some simular config, but cannot confirm anything due to the lack of ability to return to a stable configuration. We have cf-deployment and cf-deployment-concourse tasks locked, but not bosh deployment because it is not an option.

**Comment by cppforlife** [comment]
are you using bosh-dns in your deployment?

> The lookup sql-db.service.cf.internal on *IP*: no such host is repeatedly
failing.

this doesnt sound like bosh-deployment configuration i think.

**Comment by Benjamintf1** [comment]
We are, but that's kind of not our point. We had a working configuration at some point, and now it does not work. If we were able to peg our bosh-deployment, we would have no doubt that it wasn't a problem with bosh-deployment, now we are in the situation where we don't know what caused us to break.

**Comment by cppforlife** [comment]
could you share which git sha you were using before and after the change?
im somewhat skeptical that this relates to bosh-deployment.

regarding more general question, any reason not to lock down
bosh-deployment to a specific sha?

**Comment by Benjamintf1** [comment]
We had to delete the pipeline to purge our cf-deployment version, so we're not sure.

**Comment by Benjamintf1** [comment]
1) we version control our pipelines definitions, not our concourse state: a filterable version allows us to know what version we used to deploy on, allowing us to know what has changed since last deploy.

2) versioning implies a working state, id rather not go commit by commit to try amd find a working version. 

3) versioning helps with finding older and newet versions: if i am trying to go from v1 of some bosh release to v3 and have to go through v2 thats only supported by x-y versions of bosh, do you expect me to comb through commit shas or just try and find the tag v289.x on bosh-deployment.

**Comment by geofffranks** [comment]
Where does this stand currently?

**Comment by sharms** [comment]
Hi folks - currently we have three choices:
1. Follow `master`
2. Follow releases (last update 5-6 months ago)
3. Create our own releases

Any chance this can follow the same process as CF / Concourse / cf-deployment etc?

**Comment by h4xnoodle** [comment]
Thanks all for the discussion.

At this time of writing, bosh-deployment has solidified as a development tool that holds opsfiles for flexible deployments of the director. 

The `develop` branch ingests new changes for many releases as they are released themselves. Changes are promoted to `master` after running through a `create-env` and deploy test.

As there are many components feeding into bosh-deployment which can be used optionally and may or may not be used in any given deployment, and we automatically update the opsfiles/manifest, if there was a tag for each bump that would essentially translate to each commit sha being a 'version' -- also depending on which opsfiles you are personally using. Most of the commits to master should be release (cpis, bosh, releases) and stemcell updates.

Following master is our recommended practice right now. `Master` should continue to be stable and hopefully has become more stable since this issue was opened. 

Hope that helps for now, please do continue the discussion if desired. :)
