### ISSUE TITLE
No Windows stemcell for VSphere ESX

### ISSUE THREAD

**Issue by sumanth-suvarna** [cloudfoundry/bosh-deployment#201]
Hi,
I'm not sure whether this is right place to ask for Windows stemcell for VSphere ESX.
I don't find Windows 2012 R2 stemcell for VSphere ESXi in http://bosh.cloudfoundry.org/stemcells/

Is there any plans to generate Windows stemcell for VSphere ? I have a use case to implement on Windows and we use VMWare VSphere. Do let me know.

Regards.

**Comment by xtreme-sameer-vohra** [comment]
Hi @sumanth-suvarna 
Due to MSFT's licensing requirements, we are unable to distribute windows stemcells for On-Prem IaaS like vSphere.
Therefore, we publish instructions for users to be able to create their own stemcells - https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/wiki/Creating-a-vSphere-Stemcell-by-Hand

**Comment by xtreme-sameer-vohra** [comment]
I am going to close this issue. Please feel free to open another issue if you need further assistance. Alternatively, you can reach me on the Cloud Foundry slack as well.
