### ISSUE TITLE
CPU not mounted onto VM

### ISSUE THREAD

**Issue by henderjm** [cloudfoundry/bosh-deployment#299]
Since this [commit](https://github.com/cloudfoundry/bosh-deployment/commit/8d2ac2d9ea389f6a4ef3b525f6c582ffb7fa7e19) we have failing bosh-lite deployments of CFCR with error 
`failed to run Kubelet: mountpoint for cpu not found`

We have different instances where one instance has the cpu mount
```
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,relatime,rdma)
```

And another without
```
overlay on /home type overlay (rw,nodev,relatime,lowerdir=l/kSsjcqTiR11886,upperdir=/var/vcap/data/grootfs/store/privileged/images/e78a26f9-59b7-411d-7083-6e73302f3741/diff,workdir=/var/vcap/data/grootfs/store/privileged/images/e78a26f9-59b7-411d-7083-6e73302f3741/workdir)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,relatime,rdma)
/dev/sdc1 on /var/vcap/data/docker/docker type ext4 (rw,relatime,data=ordered)
/dev/sdc1 on /var/vcap/data/docker/docker/plugins type ext4 (rw,relatime,data=ordered)
```

Steps to reproduce can be found in our tracker [story](https://www.pivotaltracker.com/story/show/160415426/comments/194392703)

**Comment by pivotal-mp** [comment]
Hi @henderjm,

Stemcells don't guarantee that certain cgroups have been mounted. It is the responsibility of the release which depends on the cgroups to set them up correctly.

It seems like you're also missing the `net_cls,net_prio` entry, so maybe your mounting script has issues with the `,`?

We believe the issues is somewhere in [this script](https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/master/jobs/docker/templates/bin/cgroupfs-mount). We tested this with bpm-release and saw the `cpu,cpuacct` and `net_cls,net_prio` subsystems mounted properly. You can reference the mounting logic [here](https://github.com/cloudfoundry-incubator/bpm-release/blob/master/src/bpm/cgroups/cgroup.go).

Let us know if that helps,

@pivotal-mp && @jfmyers9, CF BOSH

**Comment by karampok** [comment]
As it seems when running xenial on a non-bosh-lite system, then there is systemd running, which make sure that the cgroups are mounted properly. In that case the above script does alter anything.
Our questions is why in a bosh-lite xenial vm we do not have the systemd?

**Comment by luan** [comment]
Hi @karampok,

A "VM" on bosh-lite is not a VM, but a container. At the risk of over-explaining myself here, a container differs for a VM or a physical machine in many ways, one of which is that they don't run their own operating systems, they merely rely on the existing kernel on their host and then provide a layer of filesystem to their users.

Part of the role of the operating system (which isn't present in containers) is starting certain processes and services upon boot, one of these services is **systemd**. And again, since there is no operating system running specifically for the container (and honestly, not even a clear concept of what "boot" is) **systemd** is never started.

Moreover, running **systemd** in containers is no trivial matter. We chose to not try to solve that problem given that it isn't necessary for the containers to work as VMs for BOSH.

Now, back to the problem at hand: **systemd** is an implementation detail of the (non-container based) stemcells and we'd prefer if release authors didn't rely on specific behaviors of it, hence @pivotal-mp's comment about release authors being responsible for setting up such **cgroups**. If there are certain aspects of the stemcell that are part of the defined surface area we will try and make sure that those are implemented in some way for all of the provided stemcell types, but as of right now, the mounting of **cgroups** isn't one of those features.

Thanks!
@luan, CF BOSH

**Comment by karampok** [comment]
Thx for the answer!

I see that making the xenial-stemcell in a bosh-lite container look exactly a real vm with xenial ubuntu is too much work without benefit.  In CFCR we should add the following part
```
+mkdir /sys/fs/cgroup/systemd || true
+mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd || true
```
because it is required by the docker daemon and it is development-only code just for the bosh-lite case.

Thanks!
Konstantinos

**Comment by henderjm** [comment]
Thanks for the input. I am happy to close this.

**Comment by MeBNoah** [comment]
hei guys, so I am facing this issue as well ... is it possible to include a fix somehow, so that we don't have to go to all workers in order to add the commands manually.

Thanks 
Cheers 
Noah
