### ISSUE TITLE
Authorization issue generating variables from credhub 2.0.2 with bosh

### ISSUE THREAD

**Issue by kansberry** [cloudfoundry/bosh-deployment#314]
Using bosh 268.3.0 with credhub 2.0.2 to deploy concourse leads to the following error during the generation of variables:

The request could not be completed because the credential does not exist or you do not have sufficient authorization.

If I fall back to https://github.com/cloudfoundry/bosh-deployment/tree/883f78b3c1277b62f9b8d7fa2c9efcf666d2c358, where credhub 1.9.3 is being used with bosh 267.5, deployment is successful. 

Has anyone seen this before and, if so, found a solution?

**Comment by h4xnoodle** [comment]
Hi @kansberry is still happening given the latest bosh-deployment with the latest credhub? Closing for now, please let us know if this happens again.

**Comment by vijayb47** [comment]
We are facing same issue. Is this a known bug? Any particular bosh/CH version that has a fix for this?

$ credhub --version
CLI Version: 2.4.0
Server Version: 2.0.2

bosh env:
Version            268.5.0 (00000000)
Director Stemcell  ubuntu-xenial/170.9
CPI                azure_cpi

Any insight is appreciated.

**Comment by h4xnoodle** [comment]
@vijayb47 what errors are you receiving? Is it happening for all variables, new variables introduced in a deployment, or otherwise? Are they global variables (beginning with a `/`)?

**Comment by vijayb47** [comment]
Thx much for the quick reply.
It is happening for any new creds. With or without preceeding "/". 

I am able to set existing creds though.

$ credhub set -n "new-cli-test" -t password -w "post5.2test"
The request could not be completed because the credential does not exist or you do not have sufficient authorization.
$ credhub set -n "/concourse/pcf-test/pcf-pipeline/new-cli-test" -t password -w "post5.2test"
The request could not be completed because the credential does not exist or you do not have sufficient authorization.
$ credhub set -n "/concourse/pcf-test/test-credmgmt/mck-root-password" -t password -w "post5.2test"
id: 1eccfea2-dad0-4a11-b8ab-68eae01de3ad
name: /concourse/pcf-test/test-credmgmt/mck-root-password
type: password
value: <redacted>
version_created_at: "2019-08-16T16:07:34Z"

**Comment by h4xnoodle** [comment]
Thanks @vijayb47 for your response. I'm currently checking with the credhub team for any insights.

-- Rebecca, BOSH

**Comment by h4xnoodle** [comment]
The credhub team suspects that for the paths you're trying, you may not have permission.

Can you try setting a new credential on the path `/concourse/pcf-test/test-credmgmt/`? or is `mck-root-password` a new credential already?

**Comment by vijayb47** [comment]
I tried a new cred under /concourse/pcf-test/test-credmgmt/ and failed with same error. I was able to set the creds under that path before the upgrade. 
I will check the Slack channel. Are new access controls implemented in 2.x? Do we need to grant access to a path after granting credhub read & write roles?

thank you for your help,

**Comment by h4xnoodle** [comment]
@vijayb47 were you able to get help from the credhub team?

Since we last spoke we've found that upgrading from 1.9.x to 2.0 introduces new permissions within credhub. https://github.com/pivotal-cf/credhub-release/releases/tag/2.0.0 (see breaking changes).

**Comment by vijayb47** [comment]
Yes. 2.0 changed the default permissions to the Credentials path. Ended up added an admin user and grant permissions to individual userid on the path /concourse/team-name/*

Something like:
echo "Setting permissions to the path matching Concourse Team path: ${eid}"
echo
echo
credhub set-permission -p "/concourse/$team/*" \
    -a "uaa-user:$(uaac user get $eid | grep ' id: ' | awk '{print $2;}')" \
    -o "read,write,delete,read_acl,write_acl"
