### ISSUE TITLE
How to increase the resource of bosh-lite vm?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#326]
Now after deploying cf-deployment and my bosh deployment to bosh-lite, the vm becomes very busy that bosh director's response is very slow or error. Is there a way to increase the cpu and memory that the bosh-lite virtual box consume?

**Comment by dpb587-pivotal** [comment]
You can change CPU and memory by editing [`virtualbox/cpi.yml`](https://github.com/cloudfoundry/bosh-deployment/blob/eea8efcbce4da16d19584ebe31994218a1460531/virtualbox/cpi.yml#L20-L22) and redeploying your director. You may need to recover or recreate your deployments after director is restored because bosh-lite is not optimized for long-running deployments.
