### ISSUE TITLE
offline installation?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh-deployment#336]
Hi all

We would really like to use `bosh-deployment` to install and manage our BOSH directors. 
However I could not find an easy way to install a director in an offline (non-internet) environment, since all URLs refer to BOSH.io.

To solve this, we have to modify the ops files containing the BOSH.io URLs to contain URLs to local `file:///`s - effectively maintaining a fork, which we would like to avoid.

Would it make sense to extract the URLs out of the opsfiles in separate opsfiles `urls-bosh-io.yml` (pointing to bosh-io) and `urls-local.yml` which points to local files (path to local files could be influenced by another var)? Happy to provide a PR!

**Comment by voelzmo** [comment]
Hey @MatthiasWinzeler,

Thanks for the issue. Possibly the ops-files in https://github.com/cloudfoundry/bosh-deployment/tree/master/misc/no-internet-access are what you are looking for? For bosh itself, there is a separate ops-file https://github.com/cloudfoundry/bosh-deployment/blob/master/local-bosh-release.yml. The CPIs don't have their own ops-files yet, I think, but this would also be a potentially worthwhile thing to have.

Would it be an option for you to use these ops-files to achieve your use-case?

**Comment by MatthiasWinzeler** [comment]
@voelzmo thanks for getting back to us!
This already looks very close to what we need (wonder how I could've missed that..).

However, important information that's lost when using these `no-internet-access` ops files is the version of the respective release (they're contained in the bosh.io url, but lost when using the `file:///`) - and we would like to use only release combinations that are 'tested'/released by you.

So a separate `local-files.yml` ops file indicating the tested versions of the releases is what we're looking for. Maybe also just a `versions.yml` ops file that contains the versions...? 

What we actually trying to achieve is a CI/CD pipelines that takes the latest bosh-deployment commit and deploys the director using the 'supported' releases (same as http://engineering.pivotal.io/post/bosh-deployed-with-concourse/, but as an offline installation). If there's another way to subscribe to the latest supported versions (ideally as a concourse input resource), we'll happily use this as an alternative.

**Comment by belinda-liu** [comment]
Hey @MatthiasWinzeler,

It sounds like you're interested in an ops file that will specify a "supported" version matrix, but I'm not sure what supported means for you. If you're interested in always deploying the latest version of various releases, assuming that you already have them downloaded (since you are operating offline) I would imagine some clever bash might just do the trick. We do autobump the versions in other ops files, but since we can't assume what releases an offline operator has downloaded, we don't update these. 
Since bosh-deployment is intended more as a dev tool for the team, I'm not sure if this particular case is one that we'll prioritize, but if you'd like to PR any kind of workaround or proposed ops file we can definitely take a look. I could see something like a `current-versions.yml` that lives in the `no-internet-access` folder that gets autobumped along with other files when a new release comes out, but I'm not sure if that satisfies your expectation of "supported".

**Comment by MatthiasWinzeler** [comment]
hi! a `current-versions.yml` with the latest versions would be perfect.

**Comment by belinda-liu** [comment]
Hey @MatthiasWinzeler, would you be interested in submitting a PR for this? As mentioned, this particular use case isn't a priority for the team, but we'll happily accept a PR to the develop branch for a latest versions ops file. 

Thanks,
@belinda-liu && @charleshansen

**Comment by Lafunamor** [comment]
Hi @belinda-liu 
Sorry for the long time without response. We've found a different way to solve this.
However, I think that this still could be of value. I'll create a PR for the file.

**Comment by Lafunamor** [comment]
@belinda-liu @charleshansen 
I'm not sure how you expect the file to look like. Can you please provide some guidance within the PR? (#368 )

**Comment by belinda-liu** [comment]
Closing per comments in: https://github.com/cloudfoundry/bosh-deployment/pull/368. Let us know if you have any other questions.
