### ISSUE TITLE
UAA release bouncing all over the place in the uaa.yml ops file

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-deployment#347]
It looks like bots are changing the version of the UAA listed in uaa.yml all over the place. 64 to 72, down to 71, then back to 64. This is very confusing when trying to figure out what version of the UAA we should actually be using, and could be dangerous if bosh-deployment reverts a version that had a schema change and now breaks the UAA when someone pulls in a new version of the ops file. Any idea what's causing this or if it can be set to track a specific version and only go forward from there? If these were intentional changes, maybe there should be notes associated with why the revert from 72 to 71 to 64, so people understand the risks of using the versions that were rolled back?

https://github.com/cloudfoundry/bosh-deployment/commits/master/uaa.yml

**Comment by jfmyers9** [comment]
Hi @geofffranks,

The reason for the churn on the UAA release version is due to fact that we discovered deployment breaking bugs with `v72`. We then tried to revert to a previous version (`v71`) as we were informed that that version may fix the issue in question. We then discovered that it was present in that version as well and then reverted back to the original working version (`v64`) in the interest of stability.

We plan on auto updating the UAA release on a more regular cadence when they fix the issue with `v72` which should hopefully catch these issues sooner and prevent there from being as much churn on the version.

Also, bosh-deployment is largely used as a development tool and does not publish releases that are known to be stable. That means that there will be some inherent risk in consuming commits directly from master.

Sorry for the inconvenience.

@jfmyers9 && @belinda-liu, CF BOSH
