### ISSUE TITLE
Credhub release not compiling against new stemcell

### ISSUE THREAD

**Issue by jontours** [cloudfoundry/bosh-deployment#364]
We are seeing this error with the latest stemcell update: 
```
Can't use release 'credhub/2.5.0'. It references packages without source code and are not compiled against stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/456.1'
```
We deploy multiple bosh directors and this only affects directors that already compiled a 2.50 release of credhub, because we are seeing this message with the broken deployments:
`Release 'credhub/2.5.0' already exists.`

So it would appear that even though the latest tarball was shown in the diff bosh isn't sensing this as a new release and hence isn't compiling it against 456.1.

Any way we can force bosh to compile the release?

Thanks!

Jon C. - cloud.gov platform team

**Comment by mfine30** [comment]
Are you seeing that error when you are deploying bosh itself or when you are trying to deploy credhub on a bosh deployed via bosh-deployment?

**Comment by jontours** [comment]
It happens while trying to deploy bosh, during the release verification phase.

**Comment by mrosecrance** [comment]
This error happens when you've uploaded a release with the same name before (even when it's compiled against another stemcell). At the moment, we only support one release of a same name at a time and you can force the upload to overwrite with a `--fix`. We have an open issue on bosh here: https://github.com/cloudfoundry/bosh/issues/2190. I'm going to close this in favor of the discussion there.

**Comment by jontours** [comment]
Thanks @mrosecrance!
