### ISSUE TITLE
showing user data (access_key, secret_key and other certs and creds)in aws vm for cf-deployments 

### ISSUE THREAD

**Issue by aarti2309** [cloudfoundry/bosh-deployment#376]
Earlier my bosh was at 268.2.0 and I upgraded it to 270.5.0 but after the upgrade, while scout scan we detected for all cf vms having user data includes bucket-name, s3-access-key, secret-key and other certs are also present, how can remove these user data or disable it.

CPI: AWS
current cf-version is 11.2.0 and Bosh is 270.5.0

**Comment by h4xnoodle** [comment]
What version of the CPI are you using?

This data was present on VMs in 268.2.0 as well. How it got there may have been different.

As of AWS CPI v73, we have made a component within the director optional. It is called the registry. It served as a repository for additional VM metadata after the VM was created. The registry is bypassed when the director is version 268.3+, Xenial stemcell line 170.6+, and AWS CPI v73. 

What this changed was how the data gets to the VM. Instead of using the registry, all VM metadata is placed within the IaaSes metadata service/on the VM instead of through the registry.

The agent component, which obtains the data from both places, collects the data and places within `/var/vcap/bosh/settings.json`. The data you're seeing has been in this file for a very long time and is crucial to bosh working properly.

**Removing or disabling any of these files will cause issues with bosh** so it's not recommended.

There are always many credentials on disk on a deployed vm, including jobs themselves.

We have a new feature in development for signing urls instead of using these credentials on disk that currently supports the DAV blobstore. S3 should be in the next release. https://github.com/cloudfoundry/bosh/releases/tag/v270.8.0

**Comment by h4xnoodle** [comment]
Closing as the credentials are intended to be there and required. Using the upcoming feature for signing URLs will help alleviate this. Please follow the next releases of bosh for more information.
