### ISSUE TITLE
virtualbox/create-env.sh "Mounting persistent disk" error with upgrade to VirtualBox 6.1 (from 6.0)

### ISSUE THREAD

**Issue by jamespollard8** [cloudfoundry/bosh-deployment#378]
We found that the recent update to VirtualBox from 6.0 -> 6.1 has broken `bosh-deployment/virtualbox/create-env.sh` with the following error:

```
Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-e8b65e9f-4e9c-47f4-459a-198a62168ea3'... Finished (00:00:01)
  Waiting for the agent on VM 'vm-65636d87-3ea9-4735-5395-69ecf9d0d78a' to be ready... Finished (00:00:33)
  Creating disk... Finished (00:00:00)
  Attaching disk 'disk-e294dc0d-e3a2-44d0-7039-82c2ebfcc1d6' to VM 'vm-65636d87-3ea9-4735-5395-69ecf9d0d78a'... Failed (00:01:12)
Failed deploying (00:01:47)
Cleaning up rendered CPI jobs... Finished (00:00:00)
Deploying:
  Creating instance 'bosh/0':
    Updating instance disks:
      Updating disks:
        Deploying disk:
          Mounting disk:
            Sending 'get_task' to the agent:
              Agent responded with error: Action Failed get_task: Task e99bae98-06be-4b4d-4099-c32229131e20 result: Mounting persistent disk: Getting real device path: Timed out getting real device path for '1ATA'
Exit code 1
```

**Comment by jfmyers9** [comment]
I've been poking at this for a day now. I'm not quite sure what is going on here, but for some reason after upgrading to Virtualbox 6.1+, the second disk (persistent storage) never becomes available on the virtual machine.

For reference we run:
```
vboxmanage storageattach 'vm-e8acd840-5f43-4221-7e53-a0e15401e852' --storagectl 'IDE' --port '1' --device '0' --type 'hdd' --medium '/home/jfmyers9/.bosh_virtualbox_cpi/disks/disk-0fdefcc0-5b76-4216-6219-c737ed981f38/disk.vmdk' --mtype 'normal'
```
This device appears attached when querying the virtual machine:
```
IDE (0, 0): /home/jfmyers9/VirtualBox VMs/vm-e8acd840-5f43-4221-7e53-a0e15401e852/Snapshots/{3110a52e-d4b6-431a-8716-1ba0253dfbad}.vmdk (UUID: 3110a52e-d4b6-431a-8716-1ba0253dfbad)
IDE (0, 1): /home/jfmyers9/.bosh_virtualbox_cpi/disks/disk-d3fc6974-9b73-4184-449b-c21a2a9e675b/disk.vmdk (UUID: c00a0870-29fb-4f8d-a734-27ebb39a084e)
IDE (1, 0): /home/jfmyers9/.bosh_virtualbox_cpi/disks/disk-0fdefcc0-5b76-4216-6219-c737ed981f38/disk.vmdk (UUID: 329a7425-3521-4b6a-8737-1e3fc7dd41ed)
```
But for some reason on the host the disk is not present:
```
.
./by-partuuid
./by-partuuid/5486c7e8-2516-4de5-9541-8812c2469bfe
./by-partuuid/fb8b624d-2f9c-415a-a587-ce8672e35153
./by-partlabel
./by-partlabel/bosh-partition-b552112d-a643-494-0
./by-partlabel/bosh-partition-b552112d-a643-494-1
./by-uuid
./by-uuid/62aae745-0240-4260-89dc-7c6faf097973
./by-uuid/2ee8ad3c-e124-48a8-8142-fd3510404c2a
./by-uuid/b73fe9d3-376f-48cf-89dd-54c7d5fb13d6
./by-path
./by-path/pci-0000:00:01.1-ata-1-part1
./by-path/pci-0000:00:01.1-ata-1
./by-path/pci-0000:00:14.0-scsi-0:0:0:0
./by-path/pci-0000:00:01.1-ata-1-part2
./by-id
./by-id/ata-VBOX_HARDDISK_VBc00a0870-4e089ab3-part1
./by-id/ata-VBOX_HARDDISK_VBc00a0870-4e089ab3-part2
./by-id/ata-VBOX_HARDDISK_VBe186c1ee-a30f9f91-part1
./by-id/ata-VBOX_HARDDISK_VBc00a0870-4e089ab3
./by-id/ata-VBOX_HARDDISK_VBe186c1ee-a30f9f91
```

I'm reaching the extent of my virtualbox knowledge, so for the time being we recommend that you use virtualbox 6.0 for local bosh environments.

**Comment by jamespollard8** [comment]
Gotcha. Thanks Jim

**Comment by jfmyers9** [comment]
We opened the following for anyone that would like to follow along: https://www.virtualbox.org/ticket/19251

**Comment by ipa-bak** [comment]
@jfmyers9 I also run into this issue and tried to analyze the root cause.
I have posted my detailed analysis at the virtualbox-cpi repository https://github.com/cppforlife/bosh-virtualbox-cpi-release/issues/18 .

In short, the virtualbox-cpi does to wrong things:
* it tries to hotplug an IDE-device, which was never supposed to work.
   * Therefore, all handling of disks should be moved to SATA
* it uses an internal / debugging tool to perform the actual disk attache, which is explicitly document as *not* notifying the guest OS (chapter 9.22, line 4, of the VirtualBox manual, revision 6.1
   * Therefore, it should do a simple `VBoxManage storageattach <vm_name> --storagectl <ctrl_name> --port <port_num> --device 0 --type hdd  --medium <file_name>` against the running VM.  No `pause` and `resume` cycle.

Unfortunately, I can't fix this myself, because I am illiterate in GO. And there seems to be no documentation of the virtualbox-cpi nor how to build a local release and then use that local release in a "create-env" call.

**Comment by lodotek** [comment]
Anyone have any luck here?

**Comment by rboykin** [comment]
Thanks @lodotek for asking. I also need. Without this support, not sure I can even really move up to Mac's Big Sur OS level since the older level of VirtualBox is not supported there.

**Comment by rboykin** [comment]
Without this fix, you cannot run on Mac, unless there is an alternative other than this fix.

**Comment by ipa-bak** [comment]
@cf-gitbot @jfmyers9 this is still a major show-stopper and gradually turns into a security problem as VirtualBox 6.0 has reached EOL and host OS versions that support VirtualBox 6.0 also go EOL ([See comment on May 19th above](https://github.com/cloudfoundry/bosh-deployment/issues/378#issuecomment-843901786)).

However, the real problem is not with the script here, but with the bosh-virtualbox-cpi implementation, see my detailed analysis and proposed solution in https://github.com/cppforlife/bosh-virtualbox-cpi-release/issues/18 .

Also the pivotal tracker at https://www.pivotaltracker.com/story/show/170320329 tracks the wrong issues as a "blocker" for this.  This is not an issue with VirtualBox itself, which works as designed.  Your internal pivotal tracker should track above mentioned issue https://github.com/cppforlife/bosh-virtualbox-cpi-release/issues/18 as blocker.

I am not sure if  https://github.com/cppforlife/bosh-virtualbox-cpi-release is still maintained, the last commit from the original author dates from July 2018, 3 years ago.  The last commit at all from June 2019, 2 years ago.  @pellared opened https://github.com/cppforlife/bosh-virtualbox-cpi-release/pull/19 to prepare for work on this (I think), which apparently went unnoticed.

So to ask directly: Is VirtualBox still a supported CPI for bosh-lite?

**Comment by jfmyers9** [comment]
Unfortunately I'm no longer involved with this project, so I can't quite help here. Might be worth looking at the current maintainers of the project for an idea of who can help.

**Comment by rboykin** [comment]
Still needed.

**Comment by 9numbernine9** [comment]
Bump for freshness.

**Comment by bgandon** [comment]
We have cloudfoundry/bosh-virtualbox-cpi-release#20 in review that should fix this.

**Comment by rboykin** [comment]
Any target date when PR https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/pull/20 will be included in a release there and that release included here?

**Comment by 9numbernine9** [comment]
Please don't close this yet @bosh-admin-bot . 😃

**Comment by rkoster** [comment]
@rboykin could you try again with https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/releases/tag/v0.2.2. It is being auto bumped into bosh-deployment as we speak (ci just needs a bit more time).

**Comment by rboykin** [comment]
@rkoster My latest attempt at using bosh-deployment worked fine for creating a virtualbox environment. 

My only remaining issue is here: https://github.com/cloudfoundry/bosh-virtualbox-cpi-release/issues/21

**Comment by rkoster** [comment]
Perfect, will close this issue then.
