### ISSUE TITLE
Unable to proceed with bosh-director deployment on Vcloud Director ("Broken pipe error while creating stemcell")

### ISSUE THREAD

**Issue by justinjosephk** [cloudfoundry/bosh-deployment#381]
Hi, 

We are trying to configure bosh-director in Vcloud but it fails during bosh-catalog creation.
Please find the details below:

1.Environment Details:
 Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-170-generic x86_64), xenial with 1 TB space availability
 
2.Installed Bosh CLI using the following links
https://bosh.io/docs/cli-v2-install/
https://github.com/cloudfoundry/bosh-cli/releases

3.Installing Bosh director using the following link in Vcloud
https://bosh.io/docs/init-vcloud/

**Default Stemcell available**: https://bosh-core-stemcells.s3-accelerate.amazonaws.com/621.29/bosh-stemcell-621.29-openstack-kvm-ubuntu-xenial-go_agent.tgz  
The above default stemcell was not working as was throwing the error as 0 .ovf files in the image, so we manually changed the stem cell to   https://bosh-core-stemcells.s3-accelerate.amazonaws.com/621.29/bosh-stemcell-621.29-vcloud-esxi-ubuntu-xenial-go_agent.tgz in the cpi.yml file. 

4.We are running the bosh create-env script using the administrator credentials who has full permissions.
We have set all the parameters of the vcloud in bosh create-env script and running the script authenticates the Vcloud but it fails when the bosh-catalog is getting created
with the following error:

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-vcloud-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vcloud-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:00:07)

Started installing CPI
  Compiling package 'ruby_vcloud_cpi/ca3bf80e18b62e4f466884a7f2f5f7eab5fbf149'... Finished (00:00:00)
  Compiling package 'bosh_vcloud_cpi_mkisofs/9e959a7865f5a568ffbfafc7d4291614f8d7c1c6'... Finished (00:00:00)
  Compiling package 'bosh_vcloud_cpi/7ceef897385bae225014c90bd92ef35e771d988a'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vcloud_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vcloud-esxi-ubuntu-xenial-go_agent/621.29'... Failed (00:00:20)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-vcloud-esxi-ubuntu-xenial-go_agent 621.29):
  CPI 'create_stemcell' method responded with error: CmdError****{"type":"Unknown","message":"Broken pipe","ok_to_retry":false}****

Exit code 1

Can anyone let us know how to fix this as we are struck at this point and unable to proceed further.

**Comment by justinjosephk** [comment]
Hi, Please let me know if anyone knows the resolution for the above issue in order for us to proceed further.

**Comment by bgandon** [comment]
Hi Justin,

In the context of one of my customers, I was told by Pivotal in 2017 that they were abandoning vCloud CPI support for BOSH in their commercial product. Customers had to use the vSphere CPI instead.

This means a lot, and it's confirmed when you look at the latest version for the vCloud CPI. See <https://github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release/releases>, It hasn't been maintained since August 2016. That is definitely a very very long time.

The BOSH Director has known a large deal of improvements and some important deprecation since 2016. BOSH v2 features only were in their infancy at the time, with the very first features just about to be implemented. Since then, BOSH v2 features have definitely settled in 2017 and have greatly transformed the way we use BOSH. It's much better. And more recently in 2019, improvements with BOSH DNS have also brought major improvements in the way we can load-balance services for BOSH-managed clusters with BOSH-native features, i.e. in a robust and consistent way across different clouds.

Also, CPIs have evolved since 2016. new endpoints have emerged and must now be implemented for the BOSH Director to properly drive vCloud. Also, your log mentions something about the registry. If I remember correctly, the registry is now completely deprecated.

All in all, the CPI vCloud is deprecated in favor of vSphere CPI. If you absolutely need to use vCloud, the vCloud maintenance has to be take over, and updates to the code have to be  submitted in order to support the latest API for BOSH CPIs. If you need more help and have budget, I might be one of the few people in the world that would be able and would agree to help you in this. In such case, don't hesitate to reach out to me by private mail.

Best,
Benjamin

**Comment by justinjosephk** [comment]
Thanks for the update Benjamin.

**Comment by h4xnoodle** [comment]
Thanks @bgandon for the excellent answer. You're definitely correct -- the vCloud CPI (where this error originates) has long since been abandoned. Thanks for raising this issue @justinjosephk.
