### ISSUE TITLE
Can't connect to director after reboot

### ISSUE THREAD

**Issue by lameventanas** [cloudfoundry/bosh-deployment#387]
After rebooting the virtualbox vm for the director, I can't connect to it anymore.
I found a similar issue from a couple of years ago and at the time the issue was that rebooting or even suspend/resume was not supported.
Is this still true?
Do I have to deploy everything again from zero after this, or can I recover what I had?
Thanks.

**Comment by jfmyers9** [comment]
Generally rebooting the bosh director on a virtualbox VM has been discouraged. This is due to the fact that the "vms" can't possibly stay running due to the fact that they are containers running locally on the machine.

I am not aware of what the previous failures were, but it appears that rebooting the director vm on virtualbox results in the ephemeral disk from being reset. This means that there are no packages or executables for `monit` to execute.

What is your use case for rebooting the virtualbox director? It seems unlikely that we are going to invest a lot of time into the virtualbox CPI as it is mainly a dev tool used for convenience. We would encourage you to re-run `create-env` if you wish to make changes to the director's VM.

**Comment by lameventanas** [comment]
I don't have a use case, I'm just unable to keep it running with 100% availability, eventually the power is cut or someone reboots the machine for some reason and then everything is gone.

People using virtualbox are the ones that need this the most, since we don't have access to more advance infrastructure and have less uptime.
