### ISSUE TITLE
BOSH api to automatically add diego cell on which containers can be deployed on .

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/bosh-deployment#426]
Detailed Description
BOSH api to automatically add diego cell or Create VM on which containers can be deployed on .

Currently a new diego cell has to be provisioned manually on Vsphere environment

Context
. We wish to automate it using scripts so that based on load a new diego cell can be provisioned automatically on cloud environment like AWS/Azure

This will help users to not only scale containers but also the underlying VMs on which containers are deployed on

Possible Implementation
Bosh vsphere CPI could provide apis to provision new diego Cells

Complexity
Medium

**Comment by psycofdj** [comment]
Hello @viju2008 

From my understanding BOSH as no particular knowledge of diego-cells and is agnostic of any king of VM under its responsibility. I doubt that a specific API endpoint would be implemented to scale diego-cells.

However, I think that scaling automatically a particular instance group is already possible using existing director's `deployments` endpoints:
- [GET current deployment manifest](https://bosh.io/docs/director-api-v1/#get-deployment) for Cloud Foundry from BOSH
- increment `/instance_groups/name=diego-cell/instances` from simple script 
- [POST updated deployment manifest deployment](https://bosh.io/docs/director-api-v1/#post-deployment)  into BOSH

The same can be achieved using the CLI:
- `bosh -d cf manifest > /tmp/cf.yml`
- increment  `/instance_groups/name=diego-cell/instances` in `/tmp/cf.yml`
- `bosh -d cf deploy /tmp/cf.yml`

Note: As far as I know, existing containers running on existing diego-cells won't be distributed on newly created cells. The cells load will remain the same until something happens on CF: app restart, app restage, app scale, new apps... etc.

**Comment by viju2008** [comment]
Thanks @psycofdj for your insights.

@psycofdj  We are trying to move additional workloads by load balancing workload to the public cloud and we want to automate it. 

We wish to keep very low capacity in the public cloud  and scale underlying diego cells (VM) and containers  when there is additional load

From scripts we can call any API . We are looking to call some BOSH or CF API to increase the diego-cells

**We have started writing some scripts for it. If we use the BOSH CLI commands given by you to change the manifest and call "cf scale" command will it start deploying new containers to the diego cells. **

**Comment by beyhan** [comment]
Hi @viju2008,

as @psycofdj already mentioned BOSH is a IaaS agnostic tool and you can use it to deploy Cloud Foundry. If you want to add additional Diego VMs to your Cloud Foundry deployment you need to increase the instances count of the the `diego-cell` instance group in CF deployment as already mention and trigger a re-deploy. BOSH will automatically provision the configured VMs and you don't need to anything, but just make sure that your IaaS account have enough capacity to launch the additional VMs.

How Cloud Foundry manages the containers is a different story. You can find more information on this in the CF docs: https://docs.cloudfoundry.org/concepts/diego/diego-auction.html

This is not the correct repository for BOSH issues because we manage hare the possible BOSH configurations. The correct one is https://github.com/cloudfoundry/bosh. I will close this issue because we provided answers to the original questions. I will also recommend for the future to discuss first the requests/questions in the BOSH Slack channel https://cloudfoundry.slack.com/archives/C02HPPYQ2.

**Comment by bgandon** [comment]
As a side note Xavier (@psycofdj) on this specific point:

> _Note: As far as I know, existing containers running on existing diego-cells won't be distributed on newly created cells. The cells load will remain the same until something happens on CF: app restart, app restage, app scale, new apps... etc._

Actually app instances now have an Identity TLS certificate that is used to access CredHub with mTLS, and expires after 24 hours. Those certificates are entirely managed by Diego. When they expire, the app instance has to be re-created with the new certification and private key.

So, as far as I've understood that feature, CF apps are actually re-balanced accross Diego cells every 24h.
