### ISSUE TITLE
Getting an error while uploading new releases and new stemcells on bosh

### ISSUE THREAD

**Issue by Manu2516789** [cloudfoundry/bosh-deployment#443]
Hi all,

I am trying to upload a new releases and new stemcells on bosh but getting this below error , I have not done any changes to my deployment or to bosh but suddenly facing this issue also none of the internal certs of bosh are expired. Please suggest what can be done to resolve this issue?

Task 1762508 | 14:10:23 | Downloading remote release: Downloading remote release (00:00:00)
                     L Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Task 1762508 | 14:10:23 | Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

AND

Task 4283

Task 4283 | 15:06:33 | Update stemcell: Downloading remote stemcell (00:00:01)
                     L Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Task 4283 | 15:06:34 | Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

Task 4283 Started  Mon Nov  7 15:06:33 UTC 2022
Task 4283 Finished Mon Nov  7 15:06:34 UTC 2022
Task 4283 Duration 00:00:01
Task 4283 error

Uploading remote stemcell 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-jammy-go_agent?v=1.44':
  Expected task '4283' to succeed but state is 'error'

Exit code 1

CERTIFICATE EXPIRY DATE INFORMATION

Certificate                         Expiry Date (UTC)     Days Left
director.ssl.cert                   2023-01-14T13:14:55Z  67
blobstore.tls.cert.ca               2023-01-14T13:15:02Z  67
director.config_server.ca_cert      2023-01-14T13:15:06Z  67
director.config_server.uaa.ca_cert  2023-01-14T13:14:53Z  67
nats.tls.ca                         2023-01-14T13:14:56Z  67
nats.tls.client_ca.certificate      2023-01-14T13:14:56Z  67
nats.tls.director.certificate       2023-01-14T13:14:59Z  67

Succeeded.

P.S.: The bosh release is 270.5.0 and uses stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent/456.27.

I am running this command from a bastion VM present in same AWS region. No security group/proxy related changes are made.

**Comment by ramonskie** [comment]
we have seen a few ppl who are running on old xenial builds reporting this issue.
its because some root certs have rotated and those root certs have not been updated as xenial stemcells are EOL since 2021
also the 456 line have been deprecated since 3 years and have not receive any updates.

my suggestion would be to upgrade your director to at least bionic
if your moving to jammy please not that you than also need to use the latest bosh release and AWS cpi.
if this is not possible i would then suggest to bump to the xenial 621 line but please keep in mind that this is also EOL.

a quick solution would be downloading the stemcell to your local machine and then use `bos upload-stemcell YOURPATH/stemcell.tgz'

**Comment by rkoster** [comment]
Stemcells older then 3 years will be cleaned up by the community: https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0010-stemcell-cleanup.md#proposal
